'use client';

import { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { useMemo } from '@/hooks/useApi';
import { formatTime, formatCurrency, getValueColor } from '@/lib/utils';
import { TrendingUp, TrendingDown, AlertCircle } from 'lucide-react';
import type { AIMemo } from '@/types/api';

interface IntelligenceMemoProps {
  symbol: string;
}

/**
 * 12-Section Intelligence Memo with Framer Motion reading mode
 * Sections fade in on scroll with sticky header for key signals
 */
export function IntelligenceMemo({ symbol }: IntelligenceMemoProps) {
  const { data: memo, isLoading, error } = useMemo(symbol);
  const [visibleSections, setVisibleSections] = useState(new Set<number>());

  if (isLoading) {
    return (
      <div className="glass-card p-8 flex items-center justify-center h-96">
        <p className="text-slate-400">Loading intelligence memo...</p>
      </div>
    );
  }

  if (error || !memo) {
    return (
      <div className="glass-card p-8 flex flex-col items-center justify-center h-96 gap-4">
        <AlertCircle size={24} className="text-bear" />
        <p className="text-slate-400">Failed to load memo</p>
      </div>
    );
  }

  const sections = [
    { id: 1, title: 'Executive Summary', content: memo.executiveSummary },
    { id: 2, title: 'Recommendation', content: getMemoRecommendation(memo.recommendation) },
    { id: 3, title: 'Scorecard', content: memo.scorecard },
    { id: 4, title: 'DCF Analysis', content: memo.dcfAnalysis },
    { id: 5, title: 'Business Moat', content: memo.businessMoat },
    { id: 6, title: 'Risk Factors', content: memo.riskFactors },
    { id: 7, title: 'Macro Context', content: memo.macroContext },
    { id: 8, title: 'Technical View', content: memo.technicalView },
    { id: 9, title: 'Sector Comparison', content: memo.sectorComparison },
    { id: 10, title: 'Valuation Summary', content: memo.valuationSummary },
    { id: 11, title: 'Disclaimer', content: memo.disclaimer },
    { id: 12, title: 'Generated', content: `By: ${memo.generatedBy}\nAt: ${formatTime(memo.generatedAt, 'datetime')}` },
  ];

  return (
    <div className="space-y-6">
      {/* Sticky Header with Key Signals */}
      <motion.div
        sticky={true}
        className="glass-card p-6 border-b border-white/5 sticky top-0 z-20"
      >
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-2xl font-bold text-slate-100">{symbol}</h2>
            <p className="text-sm text-slate-400 mt-1">
              Intelligence Memo • Last updated {formatTime(memo.generatedAt, 'time')}
            </p>
          </div>

          {/* Signal Badge */}
          {memo.recommendation && (
            <motion.div
              initial={{ scale: 0.8 }}
              animate={{ scale: 1 }}
              className={`
                px-4 py-2 rounded-lg font-semibold text-center
                ${
                  memo.recommendation.signal === 'BUY'
                    ? 'bg-bull/20 text-bull'
                    : memo.recommendation.signal === 'SELL'
                    ? 'bg-bear/20 text-bear'
                    : 'bg-caution/20 text-caution'
                }
              `}
            >
              {memo.recommendation.signal}
            </motion.div>
          )}
        </div>
      </motion.div>

      {/* 12 Sections with Fade-in on Scroll */}
      <div className="space-y-4">
        {sections.map((section, idx) => (
          <MemoSection
            key={section.id}
            section={section}
            index={idx}
            isVisible={visibleSections.has(section.id)}
            onVisible={() => {
              setVisibleSections((prev) => new Set([...prev, section.id]));
            }}
          />
        ))}
      </div>

      {/* Footer */}
      <div className="glass-card p-4 text-xs text-slate-400 border-t border-white/5">
        <p>
          ⓘ This memo is generated by Gemini AI. Please perform your own due diligence before
          investing.
        </p>
      </div>
    </div>
  );
}

interface MemeSectionProps {
  section: {
    id: number;
    title: string;
    content?: string;
  };
  index: number;
  isVisible: boolean;
  onVisible: () => void;
}

function MemoSection({ section, index, isVisible, onVisible }: MemeSectionProps) {
  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting && !isVisible) {
          onVisible();
        }
      },
      { threshold: 0.1 }
    );

    const element = document.getElementById(`memo-section-${section.id}`);
    if (element) observer.observe(element);

    return () => observer.disconnect();
  }, [section.id, isVisible, onVisible]);

  return (
    <motion.div
      id={`memo-section-${section.id}`}
      initial={{ opacity: 0, y: 20 }}
      animate={isVisible ? { opacity: 1, y: 0 } : { opacity: 0, y: 20 }}
      transition={{ delay: index * 0.1, duration: 0.5 }}
      className="glass-card p-6 space-y-3"
    >
      {/* Section Title */}
      <h3 className="text-lg font-semibold text-slate-100 flex items-center gap-2">
        <span className="text-sm text-trust">{section.id.toString().padStart(2, '0')}</span>
        {section.title}
      </h3>

      {/* Section Content */}
      <div className="text-sm text-slate-300 whitespace-pre-wrap leading-relaxed">
        {section.content || 'No data available'}
      </div>
    </motion.div>
  );
}

function getMemoRecommendation(recommendation: any): string {
  if (!recommendation) return 'No recommendation available';

  let content = `Signal: ${recommendation.signal}\nConfidence: ${(recommendation.confidence * 100).toFixed(0)}%\n\n`;

  if (recommendation.entryZone) {
    content += `Entry Zone: ${recommendation.entryZone}\n`;
  }
  if (recommendation.fairValue) {
    content += `Fair Value: ${formatCurrency(recommendation.fairValue)}\n`;
  }
  if (recommendation.stopLoss) {
    content += `Stop Loss: ${formatCurrency(recommendation.stopLoss)}`;
  }

  return content;
}
